document:
  name: Open Access policy to the contributions of INGV scientific research
  description: |
    Open Access policy to the contributions of the Istituto Nazionale di Geofisica e Vulcanologia scientific research.
  tags:
    - INGV
    - data policy
    - database
    - dataset
    - scientific research
    - metadata
    - FAIR
    - contributions
