document:
  name: Open accesso to scientific contributions of INGV
  description: |
    Open Access to the scientific contributions of the Istituto Nazionale di Geofisica e Vulcanologia.
  tags:
    - INGV
    - data policy
    - database
    - dataset
    - scientific research
    - metadata
    - FAIR
    - contributions
